export const calendar = [
  {
    "id": null,
    "title": "Matematik (4K/2021MA__MA)",
    "start": "2021-12-14 09:45",
    "end": "2021-12-14 10:40",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "MA",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Matematik (4K/2021MA__MA)",
    "start": "2021-12-15 08:10",
    "end": "2021-12-15 09:15",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "MA",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Matematik (4K/2021MA__MA)",
    "start": "2021-12-16 08:10",
    "end": "2021-12-16 09:15",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "MA",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Matematik (4K/2021MA__MA)",
    "start": "2021-12-16 09:45",
    "end": "2021-12-16 10:40",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "MA",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Svenska (4K/2021SV__SV)",
    "start": "2021-12-13 08:10",
    "end": "2021-12-13 09:15",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "SV",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Svenska (4K/2021SV__SV)",
    "start": "2021-12-13 12:00",
    "end": "2021-12-13 13:20",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "SV",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Svenska (4K/2021SV__SV)",
    "start": "2021-12-14 08:10",
    "end": "2021-12-14 09:15",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "SV",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Svenska (4K/2021SV__SV)",
    "start": "2021-12-15 12:00",
    "end": "2021-12-15 13:20",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "SV",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Svenska (4K/2021SV__SV)",
    "start": "2021-12-17 09:45",
    "end": "2021-12-17 10:40",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "SV",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Arbetspass (4KB/2021ARB-PASS__ARB-PASS)",
    "start": "2021-12-14 12:10",
    "end": "2021-12-14 12:50",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "ARB-PASS",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Arbetspass (4KB/2021ARB-PASS__ARB-PASS)",
    "start": "2021-12-15 13:20",
    "end": "2021-12-15 14:00",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "ARB-PASS",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Arbetspass (4K/2021ARB-PASS__ARB-PASS)",
    "start": "2021-12-14 12:50",
    "end": "2021-12-14 13:30",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "ARB-PASS",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Arbetspass (4K/2021ARB-PASS__ARB-PASS)",
    "start": "2021-12-16 12:50",
    "end": "2021-12-16 13:30",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "ARB-PASS",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Arbetspass (4K/2021ARB-PASS__ARB-PASS)",
    "start": "2021-12-17 08:10",
    "end": "2021-12-17 09:45",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "ARB-PASS",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Idrott och hälsa (4K/2021IDH__IDH)",
    "start": "2021-12-13 09:50",
    "end": "2021-12-13 10:30",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "IDH",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Idrott och hälsa (4K/2021IDH__IDH)",
    "start": "2021-12-15 09:50",
    "end": "2021-12-15 10:30",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "IDH",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  },
  {
    "id": null,
    "title": "Musik (4KB/2021MU__MU)",
    "start": "2021-12-16 12:10",
    "end": "2021-12-16 12:50",
    "allDay": false,
    "context": "Kalle",
    "location": "",
    "text": "MU",
    "detailUrl": "/Calendar/Lecture/000000000",
    "eventType": 1,
    "className": "vk-eventtype-lecture",
    "cancelled": false,
    "cancellingEnabled": true,
    "adminAccess": false,
    "alertText": null,
    "alertUrl": null,
    "lectureId": null
  }
]
