root: true
parser: babel-eslint
extends: 
  - prettier
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - prettier
env:
  browser: true
  node: true
settings:
  react:
    version: "detect"
rules:
  # No typing in project
  "react/prop-types": "off"
  # React included automatically in Next.js
  "react/react-in-jsx-scope": "off"
  # Allow unescaped characters like '
  "react/no-unescaped-entities": "off"
