source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.2.2"

gem 'bundler'
gem 'cocoapods', '~> 1.12'
gem 'fastlane'
gem 'dotenv'
